# Generated by Django 2.1.3 on 2019-02-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciscoapp', '0011_auto_20190227_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='subchap',
            name='chp',
        ),
        migrations.RemoveField(
            model_name='subchap',
            name='sub',
        ),
        migrations.AddField(
            model_name='subject',
            name='chp',
            field=models.CharField(db_column='chp', max_length=25, null=True),
        ),
        migrations.DeleteModel(
            name='chapter',
        ),
        migrations.DeleteModel(
            name='subchap',
        ),
    ]
