# Generated by Django 2.1.3 on 2019-03-10 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciscoapp', '0012_auto_20190228_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('description', models.CharField(max_length=100)),
                ('code', models.SlugField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('description', models.CharField(max_length=100)),
                ('code', models.SlugField(primary_key=True, serialize=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciscoapp.VehicleBrand')),
            ],
        ),
    ]
