# Generated by Django 2.2.3 on 2019-08-29 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciscoapp', '0013_vehiclebrand_vehiclemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='chapter123',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='username', max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('points', models.IntegerField(db_column='points', default=0)),
            ],
        ),
        migrations.CreateModel(
            name='subject123',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='brand',
        ),
        migrations.DeleteModel(
            name='VehicleBrand',
        ),
        migrations.DeleteModel(
            name='VehicleModel',
        ),
        migrations.AddField(
            model_name='chapter123',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciscoapp.subject123'),
        ),
    ]
